### ISSUE TITLE
Can we get a new hex publish?

### ISSUE THREAD

**Issue by ConnorRigby** [trapped/elixir-rsa#2]
It'd be nice to get a new version to hex with the new changes.

**Comment by trapped** [comment]
Yes, of course! Sorry, I haven't kept up with Elixir. I'm gonna push it to
hex.pm this weekend if I have some time.

**Comment by jalcine** [comment]
Bumping this!

**Comment by trapped** [comment]
> Bumping this!

On it! I'm pushing the version to 1.0.0 as this package has been stable for more than a year.

**Comment by trapped** [comment]
@jalcine @ConnorRigby if you're still interested: https://hex.pm/packages/rsa/1.0.0

**Comment by jalcine** [comment]
On Thursday, November 21, 2019 8:01:09 AM PST Giorgio Pellero wrote:
> > Bumping this!
> 
> On it! I'm pushing the version to 1.0.0 as this package has been stable for
> more than a year.

Nice, thank you!


Principal software consultant at black.af[1].
I live at jacky.wtf[2].

Let's do this.

--------
[1] https://black.af/?utm_medium=email-signature
[2] https://jacky.wtf/?utm_medium=email-signature
